import { Globe2, Newspaper, ShieldAlert } from "lucide-react";

const useCases = [
  {
    title: "Journalism",
    description: "Authenticate breaking news footage and protect editorial integrity.",
    icon: Newspaper,
  },
  {
    title: "Law & Governance",
    description: "Verify evidence and combat digital impersonation in investigations.",
    icon: ShieldAlert,
  },
  {
    title: "Social Media",
    description: "Monitor viral content and flag manipulated media before it spreads.",
    icon: Globe2,
  },
];

export default function TrustEducation() {
  return (
    <section className="mx-auto max-w-6xl px-6 py-16 space-y-12">
      <div className="text-center max-w-3xl mx-auto">
        <p className="text-sm uppercase tracking-[0.2em] text-indigo-600 dark:text-indigo-300">Trust & Education</p>
        <h2 className="text-3xl md:text-4xl font-semibold mt-3">What are deepfakes?</h2>
        <p className="text-slate-600 dark:text-slate-300 mt-4">
          Deepfakes are synthetic media generated by AI models that mimic real faces, voices, or scenes. DeepGuard
          uncovers subtle inconsistencies to protect audiences and decision makers.
        </p>
      </div>
      <div className="grid gap-6 md:grid-cols-2">
        <div className="glass-card rounded-3xl p-6 space-y-4">
          <h3 className="text-xl font-semibold">Why detection matters</h3>
          <p className="text-sm text-slate-600 dark:text-slate-300">
            Trustworthy media is foundational to public safety and reputation management. DeepGuard helps teams
            respond quickly, align on evidence, and communicate with transparency.
          </p>
          <div className="rounded-2xl bg-white/70 dark:bg-white/10 p-4">
            <svg
              viewBox="0 0 200 120"
              className="w-full"
              role="img"
              aria-label="Illustration of secure verification"
            >
              <rect x="10" y="20" width="180" height="80" rx="20" fill="#1E293B" opacity="0.2" />
              <circle cx="60" cy="60" r="22" fill="#6366F1" opacity="0.6" />
              <rect x="90" y="40" width="70" height="12" rx="6" fill="#22C55E" opacity="0.7" />
              <rect x="90" y="60" width="50" height="10" rx="5" fill="#94A3B8" opacity="0.7" />
            </svg>
          </div>
        </div>
        <div className="glass-card rounded-3xl p-6 space-y-4">
          <h3 className="text-xl font-semibold">How DeepGuard helps</h3>
          <ul className="space-y-3 text-sm text-slate-600 dark:text-slate-300">
            <li className="flex items-start gap-3">
              <span className="h-2 w-2 rounded-full bg-emerald-400 mt-2" />
              Automated anomaly detection and forensic scoring.
            </li>
            <li className="flex items-start gap-3">
              <span className="h-2 w-2 rounded-full bg-emerald-400 mt-2" />
              Human-readable explanations for every verdict.
            </li>
            <li className="flex items-start gap-3">
              <span className="h-2 w-2 rounded-full bg-emerald-400 mt-2" />
              Collaboration-ready reporting and audit trails.
            </li>
          </ul>
          <div className="rounded-2xl bg-white/70 dark:bg-white/10 p-4">
            <svg
              viewBox="0 0 200 120"
              className="w-full"
              role="img"
              aria-label="Illustration of collaborative analysis"
            >
              <rect x="20" y="25" width="160" height="70" rx="18" fill="#0F172A" opacity="0.2" />
              <circle cx="60" cy="60" r="18" fill="#38BDF8" opacity="0.7" />
              <circle cx="100" cy="60" r="18" fill="#6366F1" opacity="0.7" />
              <circle cx="140" cy="60" r="18" fill="#22C55E" opacity="0.7" />
            </svg>
          </div>
        </div>
      </div>
      <div className="grid gap-6 md:grid-cols-3">
        {useCases.map((item) => (
          <div key={item.title} className="glass-card rounded-3xl p-6 hover:shadow-glow transition">
            <div className="h-12 w-12 rounded-2xl bg-indigo-500/10 flex items-center justify-center text-indigo-500">
              <item.icon className="h-5 w-5" aria-hidden />
            </div>
            <h4 className="text-lg font-semibold mt-4">{item.title}</h4>
            <p className="text-sm text-slate-600 dark:text-slate-300 mt-2">{item.description}</p>
          </div>
        ))}
      </div>
    </section>
  );
}
